### ISSUE TITLE
KawaiiStuff+ Wardrobe Addon

### ISSUE THREAD

**Issue by SirBumpleton** [Silverfeelin/Starbound-Wardrobe-Addons#32]
Hello! I am the owner of the KawaiiStuff+, and I would love if you made a workshop addon to my mod, or tell me how to do it!

[Here's the link!](https://steamcommunity.com/sharedfiles/filedetails/?id=1683606374)

**Comment by SirBumpleton** [comment]
Since I add content over time, it would be nice if I knew how to support the clothing that may be added in future updates of KawaiiStuff+.

**Comment by Silverfeelin** [comment]
You can find all the information you need on the item fetcher wiki:
https://github.com/Silverfeelin/Starbound-WardrobeItemFetcher/wiki

The overview provides some basic information while the installation and usage page should tell you everything you need.

Please let me know if you need further help with any of the steps.

**Comment by Silverfeelin** [comment]
@SirBumpleton Any progress? I'm fine with helping out if you can't figure things out or want me to make the add-on instead.

**Comment by SirBumpleton** [comment]
I've put on the side Starbound modding for a while, as I've been recently busy with college and piqued with other interests. So, if possible, I'd desire for you to make it if you have time. I'd have done it myself otherwise, but recent events drove me off. Thank you.

**Comment by Silverfeelin** [comment]
I've gone ahead and made the add-on. I thought the maid outfit looked cute so I used that for the preview image. Thanks for opening this issue!

https://steamcommunity.com/sharedfiles/filedetails/?id=1720283530
