### ISSUE TITLE
The Kazdra

### ISSUE THREAD

**Issue by MyntiTheKazdra** [Silverfeelin/Starbound-Wardrobe-Addons#33]
https://steamcommunity.com/sharedfiles/filedetails/?id=767787220&searchtext=kazdra

**Comment by Silverfeelin** [comment]
Thanks for the request. I don't know when I'll be able to get to this (and other requests I've yet to add to the list).

If you have any aptitude for modding yourself you could take a loot at the item fetcher wiki to make the add-on yourself. If not, just believe I'll get to it eventually (probably in April).
[Wardrobe Item Fetcher Wiki](https://github.com/Silverfeelin/Starbound-WardrobeItemFetcher)
