### ISSUE TITLE
Neki Race Wardrobe 

### ISSUE THREAD

**Issue by Ruikio** [Silverfeelin/Starbound-Wardrobe-Addons#49]
[Neki Race Mod](https://steamcommunity.com/sharedfiles/filedetails/?id=2611501999)

The Neki seem to have gained a lot of popularity. There is even mods Nekifying everything! Would love to recolor some of their stuff.

**Comment by Silverfeelin** [comment]
Thanks for the suggestion. Here you go:
https://steamcommunity.com/sharedfiles/filedetails/?id=2902203495

**Comment by Silverfeelin** [comment]
Oops, it's already supported. I removed the add-on.

If you just want to recolor more than the options it already has then you could use  Green's Dye Suite which works nicely with the Wardrobe https://steamcommunity.com/sharedfiles/filedetails/?id=1666272764
